stages:
  - build
  - docker-build
  
variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build

  image: openjdk:8-jdk

  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
      - .gradle/loom-cache

  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle

  script: "./gradlew build"

  artifacts:
    expire_in: 1 weeks
    paths:
      - build/libs/*

.docker-init: &dockerInit
  stage: docker-build

  image: docker:latest

  services:
    - docker:dind

  before_script:
    - mkdir docker/app/minecraft/mods || true
    - cp build/libs/Galaxy.jar docker/app/minecraft/mods/Galaxy.jar
    - cd docker/
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true


docker-master:
  <<: *dockerInit
  
  script:
    - docker build --cache-from "$CI_REGISTRY_IMAGE:latest" --tag "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    
  only:
    - master

docker-tags:
  <<: *dockerInit

  script:
    - docker build --pull --cache-from "$CI_REGISTRY_IMAGE" -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    
  only:
    - tags

docker-ref:
  <<: *dockerInit

  script:
    - docker build --pull --cache-from "$CI_REGISTRY_IMAGE" -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

  only:
    - branches

  except:
    - master