/*
 * OKTW Galaxy Project
 * Copyright (C) 2018-2025
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package one.oktw.galaxy.item.gui

enum class GuiIcon(val value: String) {
    NONE(""),
    HAMMER_3X("3x_hammer"),
    MAGNIFIER_3X("3x_magnifier"),
    PEN_3X("3x_pen"),
    A_TO_Z("a_to_z"),
    ADMINISTRATOR("administrator"),
    AIM("aim"),
    BLOODY_SWORD("bloody_sword"),
    COG("cog"),
    COMPARING_DISTANCE("comparing_distance"),
    DIAMOND_SHAPE("diamond_shape"),
    ERASE("erase"),
    ERASER("eraser"),
    ENTER("enter"),
    FLASH("flash"),
    FLYING_BULLET("flying_bullet"),
    GALAXY("galaxy"),
    GALAXY_DELTA("galaxy_delta"),
    GALAXY_WITH_CHECK_MARK("galaxy_with_check_mark"),
    GALAXY_WITH_COG("galaxy_with_cog"),
    GALAXY_WITH_EXCLAMATION_MARK("galaxy_with_exclamation_mark"),
    GALAXY_WITH_MINUS_SIGN("galaxy_with_minus_sign"),
    GALAXY_WITH_PLUS_SIGN("galaxy_with_plus_sign"),
    GALAXY_WITH_QUESTION_MARK("galaxy_with_question_mark"),
    IMPACT("impact"),
    IN_AND_OUT("in_and_out"),
    INFO("info"),
    LEAVE("leave"),
    LIST("list"),
    MAGIC("magic"),
    MAGNIFIER("magnifier"),
    MEMBER("member"),
    MESSAGE("message"),
    OPEN_CHEST("open_chest"),
    PEN("pen"),
    PENETRATE("penetrate"),
    PERIOD_OF_TEMPERATURE_CHANGE("period_of_temperature_change"),
    PERSON_WITH_COG("person_with_cog"),
    PERSON_WITH_EXCLAMATION_MARK("person_with_exclamation_mark"),
    PERSON_WITH_MINUS_SIGN("person_with_minus_sign"),
    PERSON_WITH_PLUS_SIGN("person_with_plus_sign"),
    PERSON_WITH_QUESTION_MARK("person_with_question_mark"),
    PLANET_DARK("planet_dark"),
    PLANET_HOT("planet_hot"),
    PLANET_NEUTRAL("planet_neutral"),
    PLANET_WITH_LIST("planet_with_list"),
    POWER_OFF("power_off"),
    POWER_ON("power_on"),
    RISE("rise"),
    SQUARES("squares"),
    STARDUST_JAR("stardust_jar"),
    STARS("stars"),
    STUN("stun"),
    TEMPERATURE_DECREASE("temperature_decrease"),
    TEMPERATURE_INCREASE("temperature_increase"),
    TEMPERATURE_MAXIMUM("temperature_maximum"),
    TEMPERATURE_MINIMUM("temperature_minimum"),
    TRIGGER("trigger"),
    TYPING("typing"),
    UNKNOWN_PLANET("unknown_planet"),
    UNKNOWN_PLANET_WITH_PLUS_SIGN("unknown_planet_with_plus_sign"),
    UPGRADE("upgrade"),
    ZERO_TO_NINE("zero_to_nine"),
    ARROWHEAD_UP("arrowhead_up"),
    ARROWHEAD_DOWN("arrowhead_down"),
    ARROWHEAD_LEFT("arrowhead_left"),
    ARROWHEAD_RIGHT("arrowhead_right"),
    GRAYED_ARROWHEAD_UP("grayed_arrowhead_up"),
    GRAYED_ARROWHEAD_DOWN("grayed_arrowhead_down"),
    GRAYED_ARROWHEAD_LEFT("grayed_arrowhead_left"),
    GRAYED_ARROWHEAD_RIGHT("grayed_arrowhead_right"),
    ARROW_UP("arrow_up"),
    ARROW_DOWN("arrow_down"),
    ARROW_LEFT("arrow_left"),
    ARROW_RIGHT("arrow_right"),
    GRAYED_ARROW_UP("grayed_arrow_up"),
    GRAYED_ARROW_DOWN("grayed_arrow_down"),
    GRAYED_ARROW_LEFT("grayed_arrow_left"),
    GRAYED_ARROW_RIGHT("grayed_arrow_right"),
    CHECK_MARK("check_mark"),
    CROSS_MARK("cross_mark"),
    GRAYED_CHECK_MARK("grayed_check_mark"),
    GRAYED_CROSS_MARK("grayed_cross_mark"),
    PLUS_SIGN("plus_sign"),
    MINUS_SIGN("minus_sign"),
    EXCLAMATION_MARK("exclamation_mark"),
    QUESTION_MARK("question_mark"),
    ANONYMOUS("anonymous"),
    PERSON("person"),
    PEOPLE("people"),
    NUMBER_0("number_0"),
    NUMBER_1("number_1"),
    NUMBER_2("number_2"),
    NUMBER_3("number_3"),
    NUMBER_4("number_4"),
    NUMBER_5("number_5"),
    NUMBER_6("number_6"),
    NUMBER_7("number_7"),
    NUMBER_8("number_8"),
    NUMBER_9("number_9"),
    UNDERSCORE("underscore"),
    POSITIVE("positive"),
    NEGATIVE("negative"),
}
