name: Galaxy Actions
on: [push, pull_request, workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
      - name: cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # 5.0.5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle/loom-cache
          key: caches-${{ hashFiles('build.gradle.kts', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            caches-
      - name: JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # 5.2.0
        with:
          distribution: "temurin"
          java-version: "25"
      - name: Gradle
        uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      - name: Build
        run: ./gradlew --no-daemon build
      - name: Upload-Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: jar
          path: build/libs/Galaxy.jar

  Docker-image:
    needs: Build
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      REGISTRY_IMAGE: harbor.k8s.oktw.one/galaxy/galaxy
      USERNAME: ${{ secrets.OKTW_HARBOR_USERNAME }}
      PASSWORD: ${{ secrets.OKTW_HARBOR_PASSWORD }}
    steps:
      - name: Env
        shell: bash
        run: echo IMAGE_TAG=$([ "$GITHUB_REF" = "refs/heads/master" ] && echo "latest" || ([ "$GITHUB_EVENT_NAME" = 'pull_request' ] && echo pr-${{github.event.pull_request.number}} || echo ${GITHUB_REF##*/})) >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          submodules: recursive
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # 8.0.1
        with:
          name: jar
          path: docker/mods/Galaxy.jar
      - name: login
        if: env.USERNAME != '' && env.PASSWORD != ''
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # 4.1.0
        with:
          registry: harbor.k8s.oktw.one
          username: ${{ secrets.OKTW_HARBOR_USERNAME }}
          password: ${{ secrets.OKTW_HARBOR_PASSWORD }}
      - name: build cache
        if: github.ref == 'refs/heads/master' && env.USERNAME != '' && env.PASSWORD != ''
        working-directory: ./docker
        run: |
          docker build --build-arg BUILDKIT_INLINE_CACHE=1 --pull --cache-from $REGISTRY_IMAGE:build-cache -t $REGISTRY_IMAGE:build-cache --target builder .
          docker push $REGISTRY_IMAGE:build-cache
      - name: build
        working-directory: ./docker
        run: docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $REGISTRY_IMAGE:build-cache --cache-from $REGISTRY_IMAGE:latest -t $REGISTRY_IMAGE:$IMAGE_TAG .
      - name: push
        if: env.USERNAME != '' && env.PASSWORD != ''
        run: docker push $REGISTRY_IMAGE:$IMAGE_TAG
